name: "Upload files to Statika server"
description: "This action uploads specified files to the remote Statika server"
branding:
  color: "red"
  icon: "box"
inputs:
  token:
    description: "your Statika token"
    required: true

  storage:
    description: "address of the remote Statika server. I.e.: https://remote:8080/bucket. Bucket is optional."
    required: true

  bucket:
    description: "bucket where fields should be put. might be skipped, if storage field includes path argument."
    required: false

  directory:
    description: "directory with files to be uploaded"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"